### ISSUE TITLE
Can't install via pip or easy_install

### ISSUE THREAD

**Issue by akaRem** [closeio/Flask-gzip#12]
mac os latest, venv

```
$ pip install Flask-gzip                                                                                                                                                
Traceback (most recent call last):
  File "/Users/username/Projects/project/venv/bin/pip", line 9, in <module>
    load_entry_point('pip==1.4.1', 'console_scripts', 'pip')()
  File "/Users/username/Projects/project/venv/lib/python2.7/site-packages/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/username/Projects/project/venv/lib/python2.7/site-packages/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/Users/username/Projects/project/venv/lib/python2.7/site-packages/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Users/username/Projects/project/venv/lib/python2.7/site-packages/pip/__init__.py", line 13, in <module>
    from pip.commands import commands, get_similar_commands, get_summaries
  File "/Users/username/Projects/project/venv/lib/python2.7/site-packages/pip/commands/__init__.py", line 17, in <module>
    from pip.commands.wheel import WheelCommand
  File "/Users/username/Projects/project/venv/lib/python2.7/site-packages/pip/commands/wheel.py", line 15, in <module>
    DEFAULT_WHEEL_DIR = os.path.join(normalize_path(os.curdir), 'wheelhouse')
  File "/Users/username/Projects/project/venv/lib/python2.7/site-packages/pip/util.py", line 275, in normalize_path
    return os.path.normcase(os.path.realpath(path))
  File "/Users/username/Projects/project/venv/lib/python2.7/posixpath.py", line 368, in realpath
    return abspath(path)
  File "/Users/username/Projects/project/venv/lib/python2.7/posixpath.py", line 356, in abspath
    cwd = os.getcwd()
OSError: [Errno 2] No such file or directory


$ easy_install Flask-gzip                                                                                                                                               
Searching for Flask-gzip
Reading https://pypi.python.org/simple/Flask-gzip/
Best match: Flask-gzip 0.1
Downloading https://pypi.python.org/packages/source/F/Flask-gzip/Flask-gzip-0.1.tar.gz#md5=019281380d1fd4c4c90b5e6d8fc02549
Processing Flask-gzip-0.1.tar.gz
Writing /var/folders/h6/t51k958x72x8zt8k3_vbn5100000gn/T/easy_install-lFBr0M/Flask-gzip-0.1/setup.cfg
Running Flask-gzip-0.1/setup.py -q bdist_egg --dist-dir /var/folders/h6/t51k958x72x8zt8k3_vbn5100000gn/T/easy_install-lFBr0M/Flask-gzip-0.1/egg-dist-tmp-miAgiS
error: No such file or directory


$ python                                                                                                                                                                
Python 2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by wojcikstefan** [comment]
Hi @akaRem, are you sure everything is ok with your setup? I just successfully created a new virtual environment and installed Flask-gzip. Also your pip is quite outdated:

```
(venv)[test] pip --version
pip 6.0.6
```
